#cloud-config

package_update: true
package_upgrade: true
packages:
  - apt-transport-https
  - ca-certificates
  - curl
  - gnupg-agent
  - software-properties-common
  - git
write_files:
  - path: /usr/src/compose.yml
    content: |
      services:
        streamer:
          image: eliagenini/restreamer
          container_name: "streamer"
          restart: "always"
          ports:
            - 80:80
          environment:
            STREAM_URL: ${STREAM_URL}

        proxy:
          image: qmcgaw/gluetun
          container_name: gluetun
          cap_add:
            - NET_ADMIN
          ports:
            - 8888:8888/tcp
          volumes:
            - gluetun:/gluetun
          environment:
            - VPN_SERVICE_PROVIDER=${VPN_SERVICE_PROVIDER}
            - OPENVPN_USER=${OPENVPN_USER}
            - OPENVPN_PASSWORD=${OPENVPN_PASSWORD}
            - SERVER_COUNTRIES=${SERVER_COUNTRIES}
            - HTTPPROXY=on

      volumes:
        gluetun:
runcmd:
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -
  - add-apt-repository "deb [arch=$(dpkg --print-architecture)] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - apt-get update -y
  - apt-get install -y docker-ce docker-ce-cli containerd.io
  - systemctl enable docker
  - systemctl start docker
  - sudo docker compose -f /usr/src/compose.yml up -d